server:
  port: 8080
spring:
  application:
    name: bank-rest
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB} # для использования в контейнере используем db, в случае локального запуска на машине - localhost
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
